services:
  mongo:
    image: mongo:7.0.2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_ANALYST_DB_NAME}
      MONGO_INITDB_ANALYST_USERNAME: ${MONGO_ANALYST_USERNAME}
      MONGO_INITDB_ANALYST_PASSWORD: ${MONGO_ANALYST_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mount/mongo/data/db:/data/db
      - ./mount/mongo/data/configdb:/data/configdb
      - ./mount/mongo/initdb/createuser.sh:/docker-entrypoint-initdb.d/createuser.sh

  mongo-express:
    image: mongo-express:1.0.0-20
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: "" # to disable basic auth
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo